Type: Addin
Name: Cake.CodeGen.OpenAPI
NuGet: Cake.CodeGen.OpenAPI
Assemblies:
- /**/Cake.CodeGen.OpenAPI.dll
Repository: https://github.com/lukoerfer/cake-openapi-generator.git
ProjectUrl: https://github.com/lukoerfer/cake-openapi-generator/
Author: lukoerfer
Description: "Cake module for supporting downloading files from url's in the #load directive."
Categories:
- code generation
- openapi
TargetCakeVersion: 0.33.0
TargetFrameworks:
- netstandard2.0
AnalyzedPackageVersion: 1.0.2
AnalyzedPackageIsPrerelease: false
AnalyzedPackagePublishDate: 2020-01-29T13:53:18.5700000Z
